issues#2 travel_planing create
y-iwamoto/Original_App pull request #20
Opened 2017-11-11 04:19 UTC by y-iwamoto

旅行スケジュール一覧画面を一覧、新規登録、更新、削除実装してあります。
ユーザテーブルをまだ作成していないため、Scheduleテーブルのuser_idは直接値1を入力していますが、ログイン機能作成時のタイムングで修正しようと思っています。

2017-11-11 06:03 UTC, NaitoYuki commented on app/controllers/travel_planning_controller.rb
> +    require 'date'
require はクラス宣言の前に記述しましょう！

2017-11-11 06:05 UTC, NaitoYuki commented on app/controllers/travel_planning_controller.rb
> +    @schedule.to_date = Date.today
Date.todayは変数に入れたほうがいいですね。

2017-11-11 06:06 UTC, NaitoYuki commented on app/controllers/travel_planning_controller.rb
> +          flash[:error] = @schedule.errors.messages[:to_date][1]
ここはプライベートメソッドで共通化したほうがいいですね。

2017-11-11 06:06 UTC, NaitoYuki commented on app/controllers/travel_planning_controller.rb
> +        end
プライベートメソッド化

2017-11-11 06:11 UTC, NaitoYuki commented on app/views/travel_planning/_schedule_modal.html.erb
> +</div>
できれば、newとeditは共通化したいですね。
_form.html.erbなどで入力部分を共通化するイメージです。

2017-11-11 06:12 UTC, NaitoYuki commented on app/views/travel_planning/_schedule_modal_edit.html.erb
> +</div>
app/views/travel_planning/_schedule_modal.html.erb　と同様

2017-11-11 06:14 UTC, NaitoYuki requested changes
指摘です。

2017-11-12 02:49 UTC, y-iwamoto commented
昨日のレビューの指摘反映と管理者画面作成関連をコミットしました。

ただ旅行スケジュール一覧画面で、作成後や更新後のメッセージが、
ページジングなどで別のページに行った後、もう一度ページングのリンクで戻ると
一瞬メッセージが表示されてすぐ消える現象が起きています。

flash.nowという１回だけメッセージを表示されるというものがあるのですが、それを使うとredirectなのでメッセージが表示されなくなります。
renderにしてflash.nowを使ってもあまり状況が変わりません。
何か対処法があればご指摘お願いします。

2017-11-12 11:14 UTC, merged