Issues#3
y-iwamoto/Original_App pull request #23
Opened 2017-11-19 22:33 UTC by y-iwamoto

今回の修正でスケジュール作成時に、Schedule(スケジュール)とScheduleEachDate(スケジュール日付別)を登録・更新・削除するようにし、今回新規作成画面では表示のみとしました。

今回新規に作った画面では、カレンダーの表示とスケジュールがある場所を押下すると、次作成するスケジュール時間帯別の画面に遷移するようにしてます。
※まだ画面を作成していないため、エラーとなり遷移できません
※画像アップロードなどは、また後日追加予定

2017-11-22 06:36 UTC, NaitoYuki requested changes

2017-11-22 06:36 UTC, NaitoYuki commented on app/controllers/travel_planning_controller.rb
> +
共通的な処理はプライベートメソッド化したほうがいいですね。

2017-11-23 04:55 UTC, y-iwamoto commented
よくよく確認すると共通化できましたね
確認漏れていました。すみません。

指摘いただいたスケジュールの各日付の処理の共通化ができましたので、
再度ご確認お願いいたします。

2017-11-23 05:39 UTC, NaitoYuki commented
@y-iwamoto 良いかと思います！
こちらのプルリクエストまだプッシュしますか？
しないようであればマージしてもらってOKです！

2017-11-23 06:08 UTC, merged