issues#7 header create design repair
y-iwamoto/Original_App pull request #27
Opened 2017-12-12 21:56 UTC by y-iwamoto

・ヘッダーを追加しました。（旅行作成、スポット検索のみ）
※今後ユーザ設定やログインログアウト、通知のヘッダーは機能作成時に同時に盛り込みます。

・その他、今まで作成した機能でレイアウトの気になる点は修正

・スケジュール時間帯別作成画面で、１件目の新規作成時に削除するボタンは表示させないように修正
→削除ボタンで削除して、登録させようとするとエラーとなるため

・また同じくスケジュール時間帯別作成画面で、地図のルート確認の地図リンクを表示させるのは、２件目以降にするよう処理を追加

・スポット検索では、スケジュール時間帯別で”場所名を選択する”のリンクからスポットを選択し場所名を表示させるための、スポット検索画面にある選択ボタン（スポット一覧に表示されているボタンの右から二番目）を、ヘッダーからスポット一覧に遷移させた時は非表示にするよう処理を追加。

2017-12-13 09:22 UTC, NaitoYuki requested changes

2017-12-13 09:22 UTC, NaitoYuki commented on app/controllers/travel_planning_time_controller.rb
> +      @delete_btn_disp_flg = false
フラグ管理ではなく、view側で、スケジュール時間帯別が１軒もないということを判定したほうがいいですね。

2017-12-13 20:49 UTC, y-iwamoto commented
内藤さん
指摘していただいた点を修正いたしましたので、ご確認お願いします。

2017-12-14 07:23 UTC, NaitoYuki approved these changes

2017-12-14 07:23 UTC, merged