issues#10 favorite_spot and home create
y-iwamoto/Original_App pull request #30
Opened 2017-12-23 02:22 UTC by y-iwamoto

お気に入り画面を作らないとか言っていましたが、
最初のログイン前のHOME画面で見栄えをよくするため、実装いたしました。
今回の修正では以下の３点行っています。
ご確認お願いいたします。

⑴ログイン前のHOME画面でユーザ問わず最新登録された３件と、ユーザ問わずお気に入り登録されたスポットを最大３件表示させるように実装

⑵ログイン後のヘッダーにお気に入りスポットのリンクを作成
対象ユーザのお気に入りスポットを１０件ずつ表示
→ページングで遷移、お気に入りの変更はスポット一覧で可能

※謝って現状２件でページングされるようになっていますが、次の段階で修正します

⑶管理者側のスポット部分を追加
→データ変更や管理をしたかったため追加しましたが、
ちゃんとした修正は別の機会に修正予定

2017-12-23 07:02 UTC, NaitoYuki requested changes

2017-12-23 07:02 UTC, NaitoYuki commented on app/controllers/home_controller.rb
> +    @newest_spots.each do |newest_spot|
each_with_indexを使うと、ループ処理でカウントをすることができますね。

2017-12-23 07:02 UTC, NaitoYuki commented on app/controllers/home_controller.rb
> +      @favorite_spots_hash.store("photo"+i.to_s,@fspot_details.photos[0] == nil ? "" : @fspot_details.photos[0].photo_reference)
ここの処理は共通化できるかと。

2017-12-23 07:02 UTC, NaitoYuki commented on app/controllers/home_controller.rb
> +  def getImg
rubyでは取得メソッドに、getなどは付けないことが多いみたいです。
取得したい項目名をメソッド名にする感じです。

2017-12-23 07:02 UTC, NaitoYuki commented on app/views/home/index.html.erb
> +        <% @newest_spots_ary.each do |newest_spot| %>
each_with_index使うとよいかと。

2017-12-23 07:02 UTC, NaitoYuki commented on app/views/home/index.html.erb
> +        <% @favorite_spots_ary.each do |favorite_spot| %>
each_with_index

2017-12-27 08:24 UTC, y-iwamoto commented
内藤さん
先日ご指摘いただいていた、一番最初のHome画面の修正が完了いたしましたので、御確認お願い致します

2017-12-27 09:46 UTC, NaitoYuki approved these changes
よいかと思います！
def SpotImg　はdef spot_img
とかのほうがrubyっぽいですね！
一旦マージします。

2017-12-27 09:46 UTC, merged