Issues#13
y-iwamoto/Original_App pull request #31
Opened 2017-12-25 22:12 UTC by y-iwamoto

内藤さん。お疲れ様です。
とあるバグにはまってしまい、抜け出せません。アドバイスお願いします。

ブラウザ通知で通知を管理するようのいテーブルとしてNotification(通知テーブル)を作成しました。
User(ユーザ)テーブルとは多対多の関係にしています。
※以前やったツイッターのフォロー関係のような構造です。

User1(id)→Notification(user_id+opponent_user_id)←User2(id)

紹介画面（Intoroduction）で,ユーザをボタンで選んで押下すれば、
UserにひもづくNotificationを作成する処理を入れたのですが、user_id+opponent_user_idとかは入り、idとかcreate_atが作られず、ロールバックされる状態です。

以下のようなバリデーションが出るのですが、どこを修正すればわからなくなってきたので、ソースを見ていただきアドバイスいただけないでしょうかよろしくお願い致します。

#<ActiveRecord::RecordInvalid: バリデーションに失敗しました: Notifications of from user(※User1)を入力してください, Notifications of to user(※User2)を入力してください>

2017-12-28 05:59 UTC, y-iwamoto commented
遅くなりましたが、通知機能が完成いたしましたので、御確認お願い致します。

⑴招待画面
ユーザ名称とメールアドレスを入力して、特定のユーザに自分の作成した旅行計画を共有できるようにした
⑵ブラウザ通知とヘッダー通知件数表示
旅行計画の通知を送られたユーザは、ブラウザで通知が表示される。
通知を閉じた後、ヘッダー通知件数を表示しているベルのマークの数字がプラス１される

⑶通知確認画面（ベルーマークを押下すると遷移可能）
通知確認画面の初期状態では、未読の通知が表示される
タイトル下のリンクを押すと、既読か未読かの通知を分けて表示できる

確認するを押下→旅行計画を各日付別で時間帯別に一覧が表示される
既読（未読）にするを押下→対象の通知を既読（または未読）に変更する
削除するを押下→対象の通知を削除

※issues11,12の旅行計画の共有は、今回の対応に置き換えます
※全体のデザインの修正などは別の機会にします
※サイドパネルは特に必要ないと思ったので、全体のデザインの修正時にサイドパネルスペース分は無くそうと思います

2017-12-29 01:30 UTC, NaitoYuki requested changes

2017-12-29 01:30 UTC, NaitoYuki commented on app/controllers/introduction_controller.rb
> +    else
通知の失敗はユーザーに通知しても、対処のしようがないかと思いますので、
アプリの挙動的には、ログにエラーなどで出力するなどで対処したほうがいいかもですね。

2017-12-29 05:00 UTC, y-iwamoto commented
内藤さん
指摘部分をlog出力に変えました。
御確認お願い致します。

2017-12-29 07:00 UTC, NaitoYuki approved these changes
良いかと思います！マージします。

2017-12-29 07:00 UTC, merged