issues#33 Schedule Rspec finish
y-iwamoto/Original_App pull request #45
Opened 2018-01-10 22:17 UTC by y-iwamoto

遅くなりました。
スケジュール作成部分のRSPECのテストが完了しましたので、
ご確認お願いいたします。
テストをするにあたり２点改修しました。

⑴日付のスケジュールの開始日付と終了日付の関係チェックがうまく行っていなかったため、
エラーチェックを追加

⑵一部モーダルを出した際に、エラーを出した際メッセージがうまく表示されないことと、
再表示でページングと新規登録時のボタンが表示されないことがあったため
メッセージの修正とページングと新規登録時のボタン部分をindex.htmlから_index.htmlに移動

2018-01-12 04:10 UTC, NaitoYuki requested changes

2018-01-12 04:10 UTC, NaitoYuki commented on spec/features/schedule.rb
> +           i = i + 1
FactoryGirl.create_list　とかで好きな数データを作ることができます。
また、FactoryGirl側でsequenceでtitleに番号を振ることもできます。

2018-01-12 04:10 UTC, NaitoYuki commented on spec/features/schedule.rb
> +        expect(current_url).to include 'travel_planning_date?schedule_id=1'
schedule_id = "#{schedule.id"とかでテストデータを使うことができます。

2018-01-12 10:01 UTC, y-iwamoto commented on spec/features/schedule.rb
> +           i = i + 1
ここの部分は最初FactoryGirl側でsequenceでtitleに番号を振っていたんですけども、
そうするとそれ以降のit部分に入るたびに、連番の開始番号が1からではなく、
先ほどの連番の続きの番号が振られるため（※）、今回の形で作成しました。
（※）例：作成後１番目のitではtest_１〜１１、２番目のitではtest_１２〜２２、３番目のitではtest_２３〜３３

内藤さん的に、sequenceでit部分に入るたびに、うまく毎回titleにtest_１〜１１番号できる方法がありますでしょうか？

2018-01-12 10:02 UTC, y-iwamoto commented on spec/features/schedule.rb
> +        expect(current_url).to include 'travel_planning_date?schedule_id=1'
schedule_id = "#{schedule.id"

確かにそうですね。
修正させていただきます。

2018-01-14 03:55 UTC, NaitoYuki commented on spec/features/schedule.rb
> +           i = i + 1
@y-iwamoto  itを一つにして、その中でexpectを複数書くようにしたらどうでしょうか？

2018-01-14 12:39 UTC, y-iwamoto commented
１つ目の指摘部分はcreate_listとsequenceで連続してデータを作成するように対応しました。
itは一つの大きな塊としています

２つ目は#{}の囲いがrspecで流した際にうまく変換されなかったため、h2タグにあった"スケジュール日付"が表示されているかどうかでテストするように修正

2018-01-15 02:29 UTC, NaitoYuki approved these changes

2018-01-15 02:29 UTC, merged